# ~/.dbt/profiles.yml OR medical_warehouse/profiles.yml
medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', 5432) | int }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: public
      threads: 4
      keepalives_idle: 0