# models/schema.yml
version: 2

models:
  - name: stg_telegram_messages
    columns:
      - name: message_id
        tests:
          - not_null
          - unique

  - name: dim_channels
    columns:
      - name: channel_key
        tests:
          - not_null
          - unique

  - name: dim_dates
    columns:
      - name: date_key
        tests:
          - not_null
          - unique

  - name: fct_messages
    columns:
      - name: message_id
        tests:
          - not_null
          - unique
      - name: channel_key
        tests:
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date_key